9th sprint 1-st review
YakovMorkovkin/java-filmorate pull request #1
Opened 2022-11-24 18:35 UTC by YakovMorkovkin

2022-11-25 21:58 UTC, krylov-sergey-sergeevich requested changes
Привет, надо доработать ещё

2022-11-25 21:58 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Film f : films.values()) {
Данная проверка дублируется в методах, давай ее вынесем

2022-11-25 21:58 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(Film.DATE)) {
Валидация повторяется, давай избавимся от дублирования кода

2022-11-25 21:58 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Убрать дублирование кода

2022-11-25 21:58 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Тестов маловато

2022-11-26 08:36 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Film f : films.values()) {
Вынес в отдельный метод (проверка не совсем идентичная в методах, поля разные проверяет)

2022-11-26 08:36 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(Film.DATE)) {
написал отдельный валидатор

2022-11-26 08:37 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
убрал

2022-11-26 08:37 UTC, YakovMorkovkin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
с тестами в спринг пока не очень понял, написал пока как понял

2022-11-27 13:29 UTC, krylov-sergey-sergeevich requested changes
Привет, вижу улучшения, но давай кое над чем еще поработаем =) 

p.s про валидацию да я возможно чутка переборщил, но вынесение ее в отдельные методы заранее поможет в следующем 10 дз

2022-11-27 13:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    boolean isExist(Film film, String flag) {
Модификатор доступа + лучше все же разделить на два метода isExistFilmById и isExistFilmByName завязываться на название полей это опасная практика в switch проверках

2022-11-27 13:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
А зачем аннотация?

2022-11-27 13:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int filmId;
Лучше дать значение по умолчанию и использовать Integer

2022-11-27 13:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    int filmIdGenerator(){
Модификатор доступа

2022-11-27 13:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Autowired
Аннотация зачем?

2022-11-27 13:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    int userIdGenerator(){
Модификатор доступа

2022-11-27 13:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    boolean isExist(User user, String flag) {
Лучше разделить на два метода

2022-11-27 13:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static final ChronoLocalDate DATE = LocalDate.of(1895, 12, 28);
Точно ли мы хранить данное поле тут или может в каком утилитном классе для дат?

2022-11-27 13:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static final ChronoLocalDate DATE = LocalDate.of(1895, 12, 28);
Плюс название дать более говорящее, а то скромно DATE это забудется

2022-11-27 13:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/validator/ReleaseDateValidator.java
> +        return !date.isBefore(LocalDate.of(1895, 12, 28));
Опять дублируется дата и если допустим по ТЗ она поменяется мы уверены что мы не забудем везде исправить? Надо подумать и сделать так чтобы программа постаралась везде пользоваться только одним источником "правды"

2022-11-27 14:37 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Согласен, не разобрался, если вручную создал объект инжектировать зависимость не нужно

2022-11-27 14:37 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int filmId;
поправил

2022-11-27 14:41 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    boolean isExist(Film film, String flag) {
сделал

2022-11-27 14:47 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    int filmIdGenerator(){
указал

2022-11-27 14:47 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Autowired
поправил

2022-11-27 14:48 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    boolean isExist(User user, String flag) {
сделал

2022-11-27 14:48 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    int userIdGenerator(){
поправил

2022-11-27 14:54 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/validator/ReleaseDateValidator.java
> +        return !date.isBefore(LocalDate.of(1895, 12, 28));
вынес константы в интерфейс

2022-11-27 14:54 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static final ChronoLocalDate DATE = LocalDate.of(1895, 12, 28);
поправил

2022-11-28 05:19 UTC, krylov-sergey-sergeevich approved these changes
Привет, отлично поработали - зачет!

2022-11-28 05:19 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/constant/Constant.java
> +    public static final LocalDate FIRSTDAYOFTHECINEMA =LocalDate.of(1895, 12, 28);
FIRST_DAY_OF_THE_CINEMA = LocalDate.of(1895, 12, 28);- пробел добавить + название нижними подчеркиваниями разделить

2022-11-28 06:09 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/constant/Constant.java
> +    public static final LocalDate FIRSTDAYOFTHECINEMA =LocalDate.of(1895, 12, 28);
поправил. Мёржить теперь нужно ?

2022-11-28 06:16 UTC, merged