Develop
YakovMorkovkin/java-filmorate pull request #14
Opened 2023-01-29 21:16 UTC by YakovMorkovkin

2023-01-30 21:45 UTC, krylov-sergey-sergeevich requested changes
Привет

1) Жду readme с описанием кто что сделал и схемой проекта
2) Следующий пункт логи, вот вы выбрали алгоритмы которые хотите реализовать, я как ревьювер могу искать и проверять что все есть, но в реальном мире все алгоритмы имеют название/номер чаще и то и то, например у меня на работе дают названия на подобии TS-1 TS-2 TS-3 в документации соответственно есть эти же номера, а далее в коде в логах мы пишем "TS-1 создание того того" и если у кого-то есть вопрос по реализации он идет в документацию и ищет по номеру алгоритма. Итого: Просьба в реадми или в описание PR пронумеровать алгоритмы и добавить в логах соответствующие номера.
3) Следующий пункт исключения, во всех исключениях которые несут так или иначе бизнес смысл мы должны указывать с каким объектом (id) были проблемы 
4) Везде где можно избавиться от конструктора взамен поставив аннотацию ломбока

Проверил не все еще, тк работа большая, поэтому давайте поправим что указал и после надеюсь уже останутся мелочи.

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                        ,@RequestParam(defaultValue = "year", required = false) String sortBy) {
запятая не там

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Set<Film> filmsOfDirector = filmService.getSortedFilmsByDirectorId(directorId,sortBy);
Пробел пропущен после запятой

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ReviewController(ReviewService reviewService) {
аннотацию ломбока чтобы убрать конструктор

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new NotFoundException("Пользователь не найден");
Какой не найден? В исключение надо всегда давать подробные данные о том что произошло

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/EventDBStorage.java
> +        } else events = jdbcTemplate.query(sql, (rs, rowNum) -> makeEvent(rs), id);
Кавычки для слабых?)

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/EventDBStorage.java
> +        } else events = jdbcTemplate.query(sql, (rs, rowNum) -> makeEvent(rs), id);
Мне кажется или тут два раза запрос делаем в бд по сути одинаковый если не пусто

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        String sql1 = "DELETE FROM FILMS WHERE ID=?";
А вот вопрос разве остальные сущности не должны удалиться тк у нас каскадное удаление?

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            return Optional.ofNullable(jdbcTemplate.queryForObject(sql, (rs, rowNum) -> makeFilm(rs), id));
А разве мы не можем сделать один запрос этот и если вдруг не найден то кидается исключение EmptyResultDataAccessException e и мы его обрабатывая кидаем то что нам надо? А то сейчас как будто два запроса или я ошибаюсь

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    Mpa makeMpa(ResultSet rs) throws SQLException {
public or private вот в чем вопрос

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +    public List<Like> getAllFilms() {
Так фильмы или лайки....

2023-01-30 21:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +    public LikeDbStorage(JdbcTemplate jdbcTemplate) {
Аннотацию чтобы не было конструктора

2023-01-30 22:02 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                        ,@RequestParam(defaultValue = "year", required = false) String sortBy) {
поправил

2023-01-30 22:02 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Set<Film> filmsOfDirector = filmService.getSortedFilmsByDirectorId(directorId,sortBy);
поправил

2023-01-30 22:05 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new NotFoundException("Пользователь не найден");
поправил

2023-01-30 22:06 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/EventDBStorage.java
> +        } else events = jdbcTemplate.query(sql, (rs, rowNum) -> makeEvent(rs), id);
))) вроде допустимо, но понимаю что не best practice. поправил

2023-01-30 22:12 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            return Optional.ofNullable(jdbcTemplate.queryForObject(sql, (rs, rowNum) -> makeFilm(rs), id));
всё верно, не оптимальный вариант, поправил

2023-01-30 23:38 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/EventDBStorage.java
> +        } else events = jdbcTemplate.query(sql, (rs, rowNum) -> makeEvent(rs), id);
поправил

2023-01-30 23:40 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ReviewController(ReviewService reviewService) {
поправил

2023-01-30 23:45 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        String sql1 = "DELETE FROM FILMS WHERE ID=?";
должны )), поправил

2023-01-30 23:50 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    Mpa makeMpa(ResultSet rs) throws SQLException {
private - это вспомогательный метод класса

2023-01-30 23:53 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +    public List<Like> getAllFilms() {
Лайки. поправил

2023-01-30 23:56 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeDbStorage.java
> +    public LikeDbStorage(JdbcTemplate jdbcTemplate) {
поправил

2023-01-31 10:01 UTC, YakovMorkovkin commented
Просмотрел ещё паз проект. вроде всё по замечаниям подправил. Только про схему проекта не очень понял, обновил ER - диаграмму в readme (надеюсь то что нужно). Добавил файл GROUPE PROJECT с указанием кто-что сделал и указал в логах алгоритмы.

2023-02-01 07:24 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки, в целом уже лучше - зачет!

2023-02-01 07:24 UTC, krylov-sergey-sergeevich commented on GROUPE PROJECT.md
> +### - Функциональность  «Отзывы» PF-3
Учитывая много методов на этот функционал в будущем можно каждому методу давать название например PF-3-1 , PF-3-2 и т.д, но это не критично

2023-02-01 07:24 UTC, krylov-sergey-sergeevich commented on GROUPE PROJECT.md
> +# Групповой проект :
Вот другое дело - лайк

2023-02-01 07:24 UTC, krylov-sergey-sergeevich commented on README.md
ReadMe в идеале содержит:

1) Используемые технологии
2) Краткое описание сервисов
3) Команды описаны для старта

Ориентироваться всегда можно на "лучшие" проекты в области, например можем подглядеть 
https://github.com/rubenlagus/TelegramBots

2023-02-01 07:31 UTC, YakovMorkovkin commented on README.md
Спасибо большое :) Ушёл изучать 👍

2023-02-01 07:32 UTC, merged