10th sprint 1-st review
YakovMorkovkin/java-filmorate pull request #2
Opened 2022-12-06 18:33 UTC by YakovMorkovkin

2022-12-07 06:30 UTC, krylov-sergey-sergeevich requested changes
Привет, давай поправим следующее:

1) Везде в контроллерах сделаем лог уровня info
2) Поправим замечания
3) Надо ситуацию с исключениями улучшить, создать свои а не от Spring использовать

Буду ждать с доработками =)

2022-12-07 06:30 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(InMemoryFilmStorage inMemoryFilmStorage, FilmService filmService) {
Аннотацию от ломбок для того чтобы конструктор не писать

2022-12-07 06:30 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage inMemoryUserStorage) {
Аннотацию от ломбок для того чтобы конструктор не писать

2022-12-07 06:30 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            inMemoryUserStorage.getUsers().get(userId).getFriends().add(Long.valueOf(friendId));
Давай сделаем специальный метод у User чтобы было addFriend и сразу вся логика внутри метода скрыта

2022-12-07 06:30 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else throw new ResponseStatusException(HttpStatus.NOT_FOUND);
Почему такое исключение кидаем а не свое созданное?

2022-12-07 06:30 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            inMemoryFilmStorage.getFilmById(filmId).getLikes().remove(Long.valueOf(userId));
Давай сделаем метод удаления лайка сразу у фильма чтобы не дублировать логику

2022-12-07 06:30 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    InMemoryFilmStorage inMemoryFilmStorage;
Модификатор доступа

2022-12-07 06:30 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage inMemoryFilmStorage) {
Убираем конструктор с помощью аннотации

2022-12-07 06:30 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        inMemoryUserStorage.getUsers().get(userId).getFriends().remove(Long.valueOf(friendId));
Специальный метод удаления друга у User

2022-12-07 06:30 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    User createUser(@Valid @RequestBody User user);
А зачем аннотацию Valid именно тут?

2022-12-07 07:22 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(InMemoryFilmStorage inMemoryFilmStorage, FilmService filmService) {
done

2022-12-07 07:22 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage inMemoryUserStorage) {
done

2022-12-07 07:22 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage inMemoryUserStorage) {
done

2022-12-07 07:23 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    InMemoryFilmStorage inMemoryFilmStorage;
done

2022-12-07 07:24 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage inMemoryFilmStorage) {
done

2022-12-07 07:26 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    User createUser(@Valid @RequestBody User user);
done

2022-12-07 09:58 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else throw new ResponseStatusException(HttpStatus.NOT_FOUND);
done

2022-12-07 13:51 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            inMemoryUserStorage.getUsers().get(userId).getFriends().add(Long.valueOf(friendId));
немного "причесал" код :), вынес методы добавления/удаления друзей в класс User (ту часть которую можно вынести без добавления поля InMemoryUserStorage в класс User)

2022-12-07 13:51 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        inMemoryUserStorage.getUsers().get(userId).getFriends().remove(Long.valueOf(friendId));
done

2022-12-07 13:52 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            inMemoryFilmStorage.getFilmById(filmId).getLikes().remove(Long.valueOf(userId));
вынес методы добавления/удаления лайков в класс Film (ту часть которую можно вынести без добавления поля InMemoryFilmStorage в класс Film)

2022-12-08 08:40 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2022-12-08 09:44 UTC, merged