11th sprint 1-st review
YakovMorkovkin/java-filmorate pull request #3
Opened 2022-12-28 17:25 UTC by YakovMorkovkin

2022-12-29 19:29 UTC, krylov-sergey-sergeevich requested changes
Привет, работа неплохая, но вроде чутка переусложнена давай обсудим

1. Давай файлы в папке db в gitignore кинем, или они нужны?
2. Отметил много мест по коду которые пока смутно понятны, давай их обсудим

И прошу прощения есть вероятность что следующие проверки будут кхм с задержкой, я до 7 января буду в переодических гостях/поездах поэтому если что можно писать в пачку и там обсуждать какие то моменты быстрее чем через практикум и гитхаб.

2022-12-29 19:29 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<artifactId>com.fasterxml.jackson.core</artifactId>
Для чего это?

2022-12-29 19:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Количество фильмов в базе: {}",filmStorage.getAllFilms().size());
дважды запрашиваем список фильмов, в реальной бд это было бы 2 запроса в БД это некрасиво

2022-12-29 19:29 UTC, krylov-sergey-sergeevich commented on src/test/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Давай добавим not null в полях где требуется в всех таблицах

2022-12-29 19:29 UTC, krylov-sergey-sergeevich commented on src/test/resources/schema.sql
> +ALTER TABLE users ADD CONSTRAINT IF NOT EXISTS users_key_unique UNIQUE(email);
мы можем constaint сразу в объявление таблицы определить

2022-12-29 19:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    Optional<User> getUserById(int id);
Хороший подход использовать Optional

2022-12-29 19:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaGenreController.java
> +@RequestMapping()
Зачем аннотация если пустой параметр?

2022-12-29 19:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +    public Map<Integer, Film> films() {
Для чего эти бины ниже?

2022-12-29 19:29 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    User user;
А точно ли нам эта переменная тут нужна? Не можем мы ее в тесте объявить?

2022-12-29 19:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Component("film")
А зачем мы классы модели делаем бинами? Это относится и к последующим классам

2022-12-30 07:37 UTC, YakovMorkovkin commented on src/test/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
сделал

2022-12-30 07:37 UTC, YakovMorkovkin commented on src/test/resources/schema.sql
> +ALTER TABLE users ADD CONSTRAINT IF NOT EXISTS users_key_unique UNIQUE(email);
сделал

2022-12-30 07:42 UTC, YakovMorkovkin commented on pom.xml
> +			<artifactId>com.fasterxml.jackson.core</artifactId>
это у меня была проблемка с сериализацией, кое-что проверял, забыл удалить :)

2022-12-30 07:44 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Количество фильмов в базе: {}",filmStorage.getAllFilms().size());
понял, не подумал об этом. поправил

2022-12-30 07:49 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaGenreController.java
> +@RequestMapping()
Артефакт после копипасты ))))) поправил

2022-12-30 07:59 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +    public Map<Integer, Film> films() {
это я смотрел что как работает в спринг, экспериментировал, не удалил ))) поправил

2022-12-30 08:03 UTC, YakovMorkovkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Component("film")
спасибо большое, я когда доки читал в этот тонкий момент не въехал сразу. @Component и прочие подобные аннотации нужны только для классов которым требуется управление(инжекция зависимостей) для корректной работы. а модельные классы в этом не нуждаются. т.к. в них нет никакого функционала

2022-12-30 08:05 UTC, YakovMorkovkin commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    User user;
можно и в тесте объявить, просто я подумал повторение кода - нехорошо и реализовал так

2022-12-30 17:56 UTC, krylov-sergey-sergeevich requested changes
Привет, давай еще чутка доработаем, в целом все хорошо просто хочу убедиться что доведем до нужного качества работу =)

2022-12-30 17:56 UTC, krylov-sergey-sergeevich commented on .gitignore
> +!**/db/
Это добавлено но файлы не удалены из гита и выходит что они вольются если pr одобрить. Надо их удалить

2022-12-30 17:56 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<version>3.0.1</version>
Изучи пожалуйста что такое properties в pom файле и вынеси туда все проперти и вообще уточнить хочу ты же используешь spring-boot-starter-parent разве в таком случае нужно указывать версии спринг зависимостей? Они автоматически вроде как могут проставиться из parent

2022-12-30 17:56 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
>  CREATE TABLE IF NOT EXISTS users
В прошлой итерации забыл добавить, везде надо для varchar добавить размер

2022-12-30 17:56 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    private Film film;
Переменная объявленная такая на уровне теста это bad practice, лучше дублировать в тестах тк они могут параллельно работать и заранее должны быть полностью независимыми

2022-12-30 18:10 UTC, YakovMorkovkin commented on .gitignore
> +!**/db/
удалил

2022-12-30 18:15 UTC, YakovMorkovkin commented on src/main/resources/schema.sql
>  CREATE TABLE IF NOT EXISTS users
добавил

2022-12-30 18:15 UTC, YakovMorkovkin commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    private Film film;
понял, исправил

2022-12-30 18:53 UTC, YakovMorkovkin commented on pom.xml
> +			<version>3.0.1</version>
поправил. Прояснил для себя, что при использовании spring-boot-starter-parent входящие в него зависимости наследуют его версию, если нужно указать специфичную версию, то её можно указать для конкретной зависимости. при большом количестве зависимостей в проекте отслеживать версию каждой неудобно, через properties это конечно удобнее делать, спасибо за совет :)

2022-12-31 16:43 UTC, krylov-sergey-sergeevich approved these changes
Привет, вот теперь все отлично - зачет!

2022-12-31 21:29 UTC, merged